LEDCONTROLLER_VERSION = 1.0
LEDCONTROLLER_SITE = $(TOPDIR)/package/LEDController/driver
LEDCONTROLLER_SITE_METHOD = local
LEDCONTROLLER_LICENSE = GPLv3+

LEDCONTROLLER_DEPENDENCIES = linux

define LEDCONTROLLER_BUILD_CMDS
	$(MAKE) -C $(LINUX_DIR) $(LINUX_MAKE_FLAGS) M=$(@D)
endef

define LEDCONTROLLER_INSTALL_TARGET_CMDS
	$(MAKE) -C $(LINUX_DIR) $(LINUX_MAKE_FLAGS) M=$(@D) modules_install
endef



$(eval $(generic-package))
